name: Build, Push, and Run Docker Image

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#      - name: Build Docker Image
#        run: docker build -t candyfloss-transform-test:latest .
#      - name: Push Docker Image
#        run: docker push candyfloss-transform-test:latest
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_IO }}
      - name: Build Docker Image
        run: docker build -t ${{ env.REGISTRY }}/${{ github.repository }}:latest .
      - name: Push Docker Image
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest

  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_IO }}
      - name: Pull Docker Image
        run: docker pull ${{ env.REGISTRY }}/${{ github.repository }}:latest
      - name: Run Docker Image
        run: docker run ${{ env.REGISTRY }}/${{ github.repository }}:latest
