name: Build, Push, and Run Docker Image

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#      - name: Build Docker Image
#        run: docker build -t candyfloss-transform-test:latest .
#      - name: Push Docker Image
#        run: docker push candyfloss-transform-test:latest
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}:latest

#  run:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Pull Docker Image
#        run: docker pull candyfloss-transform-test:latest
#      - name: Run Docker Image
#        run: docker run candyfloss-transform-test:latest
